name: test

on:
  workflow_dispatch:
  push:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UNIX command check
        run: |
          uname -a
          lsb_release -a
          whoami
          id
          cat /etc/passwd
          pwd
          ls -la
          ls -la /
          sudo -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git command
        run: |
          which git
          git config -l

          echo "Make an empty commit"
          git config user.name github-actions
          git config user.email 41898282+github-actions@users.noreply.github.com
          git commit --message="Create empty commit" --allow-empty

          echo "Push"
          git push origin main
