name: test

on:
  workflow_dispatch:
  push:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UNIX command check
        run: |
          uname -a
          lsb_release -a
          whoami
          id
          cat /etc/passwd
          pwd
          ls -la
          ls -la /
          sudo -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: grep check
        run: |
          grep -E "$search" -- $file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          file: "test.txt"
          search: "\"axios\":\ \"\\^(?!0\\.21\\.1)(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\""

      - name: Check package.json
        uses: skills/action-check-file@v1
        with:
          file: "test.txt"
          search: "\"axios\"\\:\ \"\\^\\(\\?\\!0\\.21\\.1\\)\\(0\\|\\[1-9\\]\\[0-9\\]\\*\\)\\.\\(0\\|\\[1-9\\]\\[0-9\\]\\*\\)\\.\\(0\\|\\[1-9\\]\\[0-9\\]\\*\\)\\(\\?\\:-\\(\\(\\?\\:0\\|\\[1-9\\]\\[0-9\\]\\*\\|\\[0-9\\]\\*\\[a-zA-Z-\\]\\[0-9a-zA-Z-\\]\\*\\)\\(\\?\\:\\.\\(\\?\\:0\\|\\[1-9\\]\\[0-9\\]\\*\\|\\[0-9\\]\\*\\[a-zA-Z-\\]\\[0-9a-zA-Z-\\]\\*\\)\\)\\*\\)\\)\\?\\(\\?\\:\\+\\(\\[0-9a-zA-Z-\\]+\\(\\?\\:\\.\\[0-9a-zA-Z-\\]+\\)\\*\\)\\)\\?\""
