name: test

on:
  workflow_dispatch:
  push:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: UNIX command check
        run: |
          uname -a
          lsb_release -a
          whoami
          id
          cat /etc/passwd
          pwd
          ls -la
          ls -la /
          sudo -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: grep check package.json
        run: |
          grep -P "$search" -- $file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          file: "test.txt"
          search: "\"axios\":\ \"\\^(?!0\\.21\\.[01])(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\""

      - name: grep check package-lock.json
        run: |
          grep -P "$search" -- $file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          file: "test.txt"
          search: "axios-(?!0\\.21\\.[01])(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?"

      - name: Check package.json
        uses: skills/action-check-file@v1
        with:
          file: "test.txt"
          search: "\"axios\":[\ \\n\\r\\t]\"\\^(?!0\\.21\\.[01])(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\""

      - name: Check package-lock.json
        uses: skills/action-check-file@v1
        with:
          file: "test.txt"
          search: "axios-(?!0\\.21\\.[01])(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?"

      - name: Check index.md for headers
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "(?<!#)#{1,6}([\ \\t](.*))?$"

      - name: Check index.md for images
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "\\!\\[.*\\]\\(.*\\)"

      - name: Check index.md for code blocks
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "```"

      - name: Check index.md for task lists
        uses: skills/action-check-file@v1
        with:
          file: "index.md"
          search: "([\\-\\+\\*]|[0-9]+\\.)[\ \\t]+\\[[\ \\t\\fxX]\\][\ \\t\\f]+\\S.*$"

      - name: Check Hello
        uses: skills/action-check-file@v1
        with:
          file: "test.txt"
          search: "Hello from the codespace"

      - name: Check sl
        uses: skills/action-check-file@v1
        with:
          file: "test.txt"
          search: "install sl"
