name: test

on:
  workflow_dispatch:
  push:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          whoami
          id
          pwd
          ls -la
          ls -la /
          ls -la ..
          ls -la ../..
